################# nacos配置文件 #################
server:
  port: 8000

logging:
  level:
    # 这里设置的日志级别优先于log4j2.xml文件Loggers中的日志级别。
    com.fontana: info

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      main:
        url: jdbc:mysql://localhost:3306/common-upms?characterEncoding=utf8&useSSL=true&serverTimezone=Asia/Shanghai
        username: root
        password: 123456
      operation-log:
        url: jdbc:mysql://localhost:3306/common-upms?characterEncoding=utf8&useSSL=true&serverTimezone=Asia/Shanghai
        username: root
        password: 123456
      driver-class-name: com.mysql.cj.jdbc.Driver
      name: common-upms
      initialSize: 10
      minIdle: 10
      maxActive: 50
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      maxOpenPreparedStatements: 20
      validationQuery: SELECT 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      filters: stat,wall
      useGlobalDataSourceStat: true
      web-stat-filter:
        enabled: true
        url-pattern: "/*"
        exclusions: "*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*,/actuator/*"
      stat-view-servlet:
        enabled: true
        urlPattern: /druid/*
        resetEnable: true

mybatis-plus:
  # mapper-locations: classpath:com/fontana/upmsservice/mapper/xml/*Mapper.xml,com/fontana/onlineservice/mapper/xml/*Mapper.xml,com/fontana/flowservice/mapper/xml/*Mapper.xml
  mapper-locations: classpath*:com/fontana/*/mapper/xml/*Mapper.xml
  # type-aliases-package:  com.fontana.upmsservice.entity,com.fontana.onlineservice.entity,com.fontana.flowservice.entity
  type-aliases-package:  com.fontana.*.entity
  global-config:
    db-config:
      logic-delete-value: -1
      logic-not-delete-value: 1

fontana:
  application:
    # 缺省的文件上传根目录。
    uploadFileBaseDir: ./bn-resource/upload-files/upms
    # 初始化密码。
    defaultUserPassword: 123456
    # 每个微服务的url目录上下文，如(/admin/upms)，通常和网关的路由path一致。
    serviceContextPath: /admin/upms
    # 是否忽略远程调用中出现的任何错误，包括逻辑异常和系统异常。
    # 通常在调试和测试阶段设置为false，以便及时发现问题。
    ignoreRpcError: false
    # Session的数据权限信息在Redis中的过期时间(秒)。
    dataPermExpiredSeconds: 86460

  # 存储session数据的Redis，所有服务均需要，因此放到公共配置中。
  # 根据实际情况，该Redis也可以用于存储其他数据。
  # redisson的配置。每个服务可以自己的配置文件中覆盖此选项。
  redisson:
    # 如果该值为false，系统将不会创建RedissionClient的bean。
    enabled: true
    # mode的可用值为，single/cluster/sentinel/master-slave
    mode: single
    # single: 单机模式
    #   address: redis://localhost:6379
    # cluster: 集群模式
    #   每个节点逗号分隔，同时每个节点前必须以redis://开头。
    #   address: redis://localhost:6379,redis://localhost:6378,...
    # sentinel:
    #   每个节点逗号分隔，同时每个节点前必须以redis://开头。
    #   address: redis://localhost:6379,redis://localhost:6378,...
    # master-slave:
    #   每个节点逗号分隔，第一个为主节点，其余为从节点。同时每个节点前必须以redis://开头。
    #   address: redis://localhost:6379,redis://localhost:6378,...
    address: redis://localhost:6379
    # 链接超时，单位毫秒。
    timeout: 6000
    # 单位毫秒。分布式锁的超时检测时长。
    # 如果一次锁内操作超该毫秒数，或在释放锁之前异常退出，Redis会在该时长之后主动删除该锁使用的key。
    lockWatchdogTimeout: 60000
    # redis 密码，空可以不填。
    password:
    pool:
      # 连接池数量。
      poolSize: 20
      # 连接池中最小空闲数量。
      minIdle: 5

  common-online:
    # 注意不要以反斜杠(/)结尾。
    urlPrefix: /online
    # 在线表单业务数据上传资源路径
    uploadFileBaseDir: ./bn-resource/upload-files/online

    # 如果为false，OnlineOperationController中的接口将不能使用。
    operationEnabled: true
    # 注意不要以反斜杠(/)结尾。
    operationUrlPrefix: /online
    # 下面的url列表，请保持反斜杠(/)结尾。
    viewUrlList:
      - ${fontana.common-online.operationUrlPrefix}/onlineOperation/viewByDatasourceId/
      - ${fontana.common-online.operationUrlPrefix}/onlineOperation/viewByOneToManyRelationId/
      - ${fontana.common-online.operationUrlPrefix}/onlineOperation/listByDatasourceId/
      - ${fontana.common-online.operationUrlPrefix}/onlineOperation/listByOneToManyRelationId/
      - ${fontana.common-online.operationUrlPrefix}/onlineOperation/downloadDatasource/
      - ${bluetron-nb-common.common-online.operationUrlPrefix}/onlineOperation/downloadOneToManyRelation/
    editUrlList:
      - ${fontana.common-online.operationUrlPrefix}/onlineOperation/addDatasource/
      - ${fontana.common-online.operationUrlPrefix}/onlineOperation/addOneToManyRelation/
      - ${fontana.common-online.operationUrlPrefix}/onlineOperation/updateDatasource/
      - ${fontana.common-online.operationUrlPrefix}/onlineOperation/updateOneToManyRelation/
      - ${fontana.common-online.operationUrlPrefix}/onlineOperation/deleteDatasource/
      - ${fontana.common-online.operationUrlPrefix}/onlineOperation/deleteOneToManyRelation/
      - ${fontana.common-online.operationUrlPrefix}/onlineOperation/uploadDatasource/
      - ${fontana.common-online.operationUrlPrefix}/onlineOperation/uploadOneToManyRelation/

  common-flow:
    # 请慎重修改urlPrefix的缺省配置，注意不要以反斜杠(/)结尾。如必须修改其他路径，请同步修改数据库脚本。
    urlPrefix: /flow

  datafilter:
    tenant:
      # 对于单体服务，该值始终为false。
      enabled: false
    dataperm:
      enabled: true
      # 在拼接数据权限过滤的SQL时，我们会用到sys_dept_relation表，该表的前缀由此配置项指定。
      # 如果没有前缀，请使用 "" 。
      deptRelationTablePrefix: bn_