################# nacos配置文件 #################
server:
  port: 8001
#  servlet:
#    context-path: /online

logging:
  level:
    # 这里设置的日志级别优先于log4j2.xml文件Loggers中的日志级别。
    com.fontana.onlineservice: info

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/common-online?characterEncoding=utf8&useSSL=true&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

# 存储session数据的Redis，所有服务均需要，因此放到公共配置中。
# 根据实际情况，该Redis也可以用于存储其他数据。
redis:
  # redisson的配置。每个服务可以自己的配置文件中覆盖此选项。
  redisson:
    # 如果该值为false，系统将不会创建RedissionClient的bean。
    enabled: true
    # mode的可用值为，single/cluster/sentinel/master-slave
    mode: single
    # single: 单机模式
    #   address: redis://localhost:6379
    # cluster: 集群模式
    #   每个节点逗号分隔，同时每个节点前必须以redis://开头。
    #   address: redis://localhost:6379,redis://localhost:6378,...
    # sentinel:
    #   每个节点逗号分隔，同时每个节点前必须以redis://开头。
    #   address: redis://localhost:6379,redis://localhost:6378,...
    # master-slave:
    #   每个节点逗号分隔，第一个为主节点，其余为从节点。同时每个节点前必须以redis://开头。
    #   address: redis://localhost:6379,redis://localhost:6378,...
    address: redis://localhost:6379
    # 链接超时，单位毫秒。
    timeout: 6000
    # 单位毫秒。分布式锁的超时检测时长。
    # 如果一次锁内操作超该毫秒数，或在释放锁之前异常退出，Redis会在该时长之后主动删除该锁使用的key。
    lockWatchdogTimeout: 60000
    # redis 密码，空可以不填。
    password:
    pool:
      # 连接池数量。
      poolSize: 20
      # 连接池中最小空闲数量。
      minIdle: 5
      
mybatis-plus:
  mapper-locations: classpath:com/fontana/onlineservice/mapper/xml/*.xml
  type-aliases-package: com.fontana.onlineservice.entity
  global-config:
    db-config:
      logic-delete-value: -1
      logic-not-delete-value: 1

fontana:
  tracelog:
    enabled: true

  common-online:
    # 注意不要以反斜杠(/)结尾。
    operationUrlPrefix: /online
    # 在线表单业务数据上传资源路径
    uploadFileBaseDir: ./bn-resource/upload-files/online
    # 如果为false，OnlineOperationController中的接口将不能使用。
    operationEnabled: true

    # 注意不要以反斜杠(/)结尾。
    urlPrefix: /online
    # 下面的url列表，请保持反斜杠(/)结尾。
    viewUrlList:
      - ${fontana.common-online.operationUrlPrefix}/onlineOperation/viewByDatasourceId/
      - ${fontana.common-online.operationUrlPrefix}/onlineOperation/viewByOneToManyRelationId/
      - ${fontana.common-online.operationUrlPrefix}/onlineOperation/listByDatasourceId/
      - ${fontana.common-online.operationUrlPrefix}/onlineOperation/listByOneToManyRelationId/
      - ${fontana.common-online.operationUrlPrefix}/onlineOperation/downloadDatasource/
      - ${fontana.common-online.operationUrlPrefix}/onlineOperation/downloadOneToManyRelation/
    editUrlList:
      - ${fontana.common-online.operationUrlPrefix}/onlineOperation/addDatasource/
      - ${fontana.common-online.operationUrlPrefix}/onlineOperation/addOneToManyRelation/
      - ${fontana.common-online.operationUrlPrefix}/onlineOperation/updateDatasource/
      - ${fontana.common-online.operationUrlPrefix}/onlineOperation/updateOneToManyRelation/
      - ${fontana.common-online.operationUrlPrefix}/onlineOperation/deleteDatasource/
      - ${fontana.common-online.operationUrlPrefix}/onlineOperation/deleteOneToManyRelation/
      - ${fontana.common-online.operationUrlPrefix}/onlineOperation/uploadDatasource/
      - ${fontana.common-online.operationUrlPrefix}/onlineOperation/uploadOneToManyRelation/

  datafilter:
    tenant:
      # 对于单体服务，该值始终为false。
      enabled: false
    dataperm:
      enabled: true
      # 在拼接数据权限过滤的SQL时，我们会用到sys_dept_relation表，该表的前缀由此配置项指定。
      # 如果没有前缀，请使用 "" 。
      deptRelationTablePrefix: bn_