################# nacos配置文件 #################
server:
  port: 8081

spring:
  cloud:
    ## 整合sentinel，配置sentinel控制台的地址
    sentinel:
      transport:
        ## 指定控制台的地址，默认端口58858
        dashboard: 192.168.8.133:58858
        ## 默认取服务ip，我这里是配置路由器ip，因为dashboard无法连到我的局域网ip
        clientip: 192.168.9.14
        ## 默认是8719，我这里改一下，且在路由器上配置端口映射，将192.168.9.14:58719转到我的局域网ip:58719
        port: 58719
      ## Sentinel 网关流控默认的粒度是 route 维度以及自定义 API 分组维度，默认不支持 URL 粒度（若在网关流控控制台上看到了 URL 资源，就是此配置项没有置为 false）。
      filter: false
      ## 是否立即注册，为true时，服务启动就注册到dashboard，dashboard马上就能看到服务；为false时，需要有接口访问才能在dashboard上看到服务
      eager: true
      #配置限流之后，响应内容
      scg:
        fallback:
          ## 两种模式，一种是response返回文字提示信息，一种是redirect，重定向跳转，需要同时配置redirect(跳转的uri)
          ## 返回模式
          mode: response
          ## 响应的状态
          response-status: 200
          ## 响应体
          response-body: '{"code": 200,"message": "当前请求繁忙，请休息一下稍后再试哦！","success": false}'
          ## 跳转模式
#          mode: redirect
#          ## 跳转的URL
#          redirect: http://www.baidu.com
      datasource:
        # 规则名称，可自定义，此处是一个留空规则
        r1:
          nacos:
            # nacos地址
            server-addr: localhost:8848
            namespace: Common
            # nacos中配置文件的data-id
            dataId: ${spring.application.name}-sentinel-flow
            # nacos中存储规则的groupId
            groupId: DEFAULT_GROUP
            # 定义存储的规则类型,表示流控规则，主要网关类型要设成gw-flow，否则控制台看不到，普通类型设成flow
            rule-type: gw-flow
            data-type: json
        # 规则名称，可自定义，此处是个降级规则
        r2:
          nacos:
            # nacos地址
            server-addr: localhost:8848
            namespace: Common
            # nacos中配置文件的data-id
            dataId: ${spring.application.name}-sentinel-degrade
            # nacos中存储规则的groupId
            groupId: DEFAULT_GROUP
            # 定义存储的规则类型,表示降级规则
            rule-type: degrade
            data-type: json

    gateway:
      discovery:
        locator:
          enabled: false
          lower-case-service-id: true
      routes:
      - id: common-upms
        uri: lb://common-upms
        predicates:
        - Path=/admin/upms/**
        filters:
        - StripPrefix=2
        - name: Hystrix
          args:
            name: default
            fallbackUri: forward:/fallback
      - id: common-online
        uri: lb://common-online
        predicates:
          - Path=/admin/online/**
        filters:
          - StripPrefix=1
          - name: Hystrix
            args:
              name: default
              fallbackUri: forward:/fallback
      - id: common-flow
          uri: lb://common-flow
          predicates:
            - Path=/admin/flow/**
          filters:
            - StripPrefix=1
            - name: Hystrix
              args:
                name: default
                fallbackUri: forward:/fallback

redis:
  # redisson的配置。每个服务可以自己的配置文件中覆盖此选项。
  redisson:
    # 如果该值为false，系统将不会创建RedissionClient的bean。
    enabled: true
    # mode的可用值为，single/cluster/sentinel/master-slave
    mode: single
    # single: 单机模式
    #   address: redis://localhost:6379
    # cluster: 集群模式
    #   每个节点逗号分隔，同时每个节点前必须以redis://开头。
    #   address: redis://localhost:6379,redis://localhost:6378,...
    # sentinel:
    #   每个节点逗号分隔，同时每个节点前必须以redis://开头。
    #   address: redis://localhost:6379,redis://localhost:6378,...
    # master-slave:
    #   每个节点逗号分隔，第一个为主节点，其余为从节点。同时每个节点前必须以redis://开头。
    #   address: redis://localhost:6379,redis://localhost:6378,...
    address: redis://localhost:6379
    # 链接超时，单位毫秒。
    timeout: 60000
    # 单位毫秒。分布式锁的超时检测时长。
    # 如果一次锁内操作超该毫秒数，或在释放锁之前异常退出，Redis会在该时长之后主动删除该锁使用的key。
    lockWatchdogTimeout: 60000
    # redis 密码，空可以不填。
    password:
    pool:
      # 连接池数量。
      poolSize: 20
      # 连接池中最小空闲数量。
      minIdle: 5

# 配置ribbon超时时间
ribbon:
  ReadTimeout: 50000
  ConnectTimeout: 20000

hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: THREAD
          thread:
            # 超过此时间后进入熔断;这个时间应该大于后端及其ribbon的时间;否则后端接口未执行完就进入熔断
            timeoutInMilliseconds: 50000

fontana:
  application:
    # Jwt令牌加密的签名值。该值的长度要超过10个字符(过短会报错)。
    tokenSigningKey: Common-signing-key
    # Jwt令牌在Http Header中的键名称。
    tokenHeaderKey: Authorization
    # Jwt令牌刷新后在Http Header中的键名称。
    refreshedTokenHeaderKey: RefreshedToken
    # Jwt令牌过期时间(毫秒)。
    expiration: 72000000
    # 跨域的IP(http://192.168.10.10:8086)白名单列表，多个IP之间逗号分隔(* 表示全部信任，空白表示禁用跨域信任)。
    credentialIpList: "*"
    # Session会话和用户权限在Redis中的过期时间(秒)。
    sessionExpiredSeconds: 86400